import { GoogleSpreadsheet } from 'google-spreadsheet'
import { google } from 'googleapis'
export const authGoogle = new google.auth.GoogleAuth({
    keyFile: 'credentials.json',
    scopes: 'https://www.googleapis.com/auth/spreadsheets',
})

//class google sheet
export const GoogleSheetInstance = async () => {
    // Initialize the sheet - doc ID is the long id in the sheets URL
    const doc = new GoogleSpreadsheet(process.env.SPREAD_SHEET_ID)

    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    await doc.useServiceAccountAuth({
        // env var values are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL as string,
        private_key: process.env.GOOGLE_PRIVATE_KEY as string,
    })

    await doc.loadInfo() // loads document properties and worksheets

    return doc
}

//ranges of google sheet connect
export const rangeGoogleSheet = {
    product: 'sản phẩm',
}
